---
 - name: install required packages
   yum:
      name: "{{ item }}"
      state: installed
   with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
   tags: docker repo

 - name: configure repo
   shell: yum-config-manager --enable --add-rep https://download.docker.com/linux/centos/docker-ce.repo

 - name: install docker-ce
   yum:
      name: docker
      state: installed

 - name: start docker-ce
   service:
      name: docker
      state: started
      enabled: yes





